title: Eduardo Cuducos
description: Sociologist, geek, bread baker, and sports fan.
url: "http://cuducos.me"
baseurl: ""
paginate: 25
paginate_path: "/blog/:num/"

exclude: 
  - contrib/
  - Gemfile
  - Gemfile.lock
  - README.md
gems:
  - jekyll-paginate
  - jekyll-sitemap
sass:
  style: compressed
