title: Eduardo Cuducos
description: Sociologist, geek, bread baker, and sports fan.
url: "http://cuducos.me"
baseurl: ""
paginate: 25
paginate_path: "/blog/:num/"

exclude: 
  - assets/js/app.js
  - bower.json
  - bower_components/
  - contrib/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - README.md
gems:
  - jekyll-paginate
  - jekyll-sitemap
sass:
  style: compressed
