title: Eduardo Cuducos
description: Sociologist, geek, bread baker, and sports fan.
url: "http://cuducos.me"
baseurl: ""
paginate: 14
paginate_path: "/blog/:num/"

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-srcset-tag
    
exclude: 
  - assets/js/app.js
  - bower.json
  - bower_components/
  - contrib/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - README.md

keep_files:
  - media

sass:
  style: compressed

srcset:
  source: _media
  output: media
